### ISSUE TITLE
xScheduledTask - Missing Only when logged in & Run with elevated rights

### ISSUE THREAD

**Issue by dominikheeb** [PowerShell/xComputerManagement#107]
Hi
If I'm not missing anything it seems that i cannot set to run the action with higher privileges and I cannot set Only when User is logged on.

This two are important for a project I work on... would be really nice to have this implemented.

**Comment by PlagueHO** [comment]
Hi @dominikheeb ,

I can confirm that the `Run with Highest Privileges` and `Run Only when User is Logged On` \`Run whether User is Logged on or Not` has not been exposed yet in this resource.

I'll see what I can do about getting this exposed before the next release.

For reference these values are found in the `Principal` object in the ScheduledTask. The `LogonType` property of the principal needs to be set to `Interactive` to enable `Run Only when User is Logged On`. The `RunLevel` property of the principal must be set to `Highest` to enable `Run with Highest Privileges`.

We're currently not assigning a principal object to the task so there is not quite a trivial change. But it isn't major.
I did some digging and this can be set by setting the `LogonType` to `Run Only when User is Logged On`

**Comment by PlagueHO** [comment]
Hi @dominikheeb - I'm working on this now. Hope to have a dev version complete by the end of the weekend. Thanks.

**Comment by PlagueHO** [comment]
Hi @dominikheeb - I've made the changes that I think you need. They're currently in my fork:
https://github.com/PlagueHO/xComputerManagement/tree/Issue-107

Could you possibly give the new version a try and see if it does what you need? I'll then submit the PR if it looks good.

Sorry it took so long, but it turns out there are some behavior differences in `New-ScheduledTaskPrincipal` in Windows Server 2016 and Windows Server 2012R2 so it took me a while to get everything working correctly.

**Comment by PlagueHO** [comment]
I have submitted the PR to add these features, but I'm not sure it will make it into master before next release (next Wednesday I think).
